name: Build Master Release

run-name: Build master -> custom-nightly (${{ inputs.trigger_source || 'push' }})

on:
  workflow_dispatch:
    inputs:
      trigger_source:
        description: What triggered this build
        required: false
        default: manual
        type: string
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

permissions:
  contents: write
  actions: write

concurrency:
  group: rustdesk-release-custom-nightly
  cancel-in-progress: false

jobs:
  build-and-release:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: custom-nightly
